#!/usr/bin/env ruby

require_relative '../lib/framework'
require 'byebug'

server = Framework::ThinServer.new do |config|
	config[:Port] = 3000
	config[:Host] = "0.0.0.0"
end

server.daemonize
byebug
server.start
