#!/usr/bin/env ruby

require 'webrick'

# configuration is a hash
configuration = {
	# standard server port
	Port: 3000,
	# root directory to serve pages to
	DocumentRoot: File.expand_path('../../public', __FILE__)
}
# Define new webserver instance
server  = WEBrick::HTTPServer.new(configuration)

# Define action for detecting a Ctrl+C
# Supresses miscallenous error output
trap('SIGINT') do
	next if @stopping # ensures that hitting Ctrl+C multiple times doesn't interrupt the server
	@stopping = true
	print "\r"
	server.logger.info "Shutdown signal received!"
	sleep(1)
	server.stop
end
@stopping = false

# Start the webserver
server.start
