#!/usr/bin/env ruby
$0 = "thin_server"
require_relative '../lib/framework'
require 'byebug'

server = Framework::ThinServer.new do |config|
	config[:Port] = 3000
	config[:Host] = "0.0.0.0"
    config[:max_connections] = 200
end

# If an argument is run with the script, the server will run in
#   # verbose mode, so that incoming packets can be tracked without
#   # having to tail the log file
server.daemonize if ARGV.empty?
server.start
